update glpi_computers set entities_id = 4 where name = 'DIAMANTE';
update glpi_networkports set entities_id = 4 where items_id = (select id from glpi_computers where name = 'DIAMANTE') and itemtype = 'Computer';
update glpi_computers set entities_id = 4 where name = 'ESMERALDA';
update glpi_networkports set entities_id = 4 where items_id = (select id from glpi_computers where name = 'ESMERALDA') and itemtype = 'Computer';
update glpi_computers set entities_id = 4 where name = 'RUBI';
update glpi_networkports set entities_id = 4 where items_id = (select id from glpi_computers where name = 'RUBI') and itemtype = 'Computer';
update glpi_computers set entities_id = 4 where name = 'SAFIRA';
update glpi_networkports set entities_id = 4 where items_id = (select id from glpi_computers where name = 'SAFIRA') and itemtype = 'Computer';
update glpi_computers set entities_id = 4 where name = 'SIGFIS';
update glpi_networkports set entities_id = 4 where items_id = (select id from glpi_computers where name = 'SIGFIS') and itemtype = 'Computer';
