update glpi_computers set entities_id = 1 where name = 'Ararajuba';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Ararajuba') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Belinda';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Belinda') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Bianca';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Bianca') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Bigua';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Bigua') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Bigua';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Bigua') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Cale';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Cale') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Calice';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Calice') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Calisto';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Calisto') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Censo';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Censo') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Centaurus';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Centaurus') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Centreon';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Centreon') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Charon';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Charon') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Cilene';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Cilene') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Cupido';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Cupido') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Deimos';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Deimos') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Desdemona';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Desdemona') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Despina';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Despina') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Dione';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Dione') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Easy';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Easy') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Ged';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Ged') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = '01';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = '01') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Easy';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Easy') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Ged';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Ged') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = '02';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = '02') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Easy';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Easy') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Ged';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Ged') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = '03';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = '03') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Easy';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Easy') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Ged';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Ged') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = '04';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = '04') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Edge-OCS';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Edge-OCS') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Epmeteu';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Epmeteu') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Europa';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Europa') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'FWSEEDUC';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'FWSEEDUC') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Fobos';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Fobos') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Ganimedes';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Ganimedes') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Hati';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Hati') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Himaleo';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Himaleo') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Hiperion';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Hiperion') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'IO';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'IO') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'JUPITER';
update glpi_networkports set entities_id = 1 where items_id in (select id from glpi_computers where name = 'JUPITER') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Jacare';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Jacare') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Jaguatirica2';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Jaguatirica2') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Japeto';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Japeto') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Kari';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Kari') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Kore';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Kore') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Larissa';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Larissa') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Lua';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Lua') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Marte';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Marte') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Nagios';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Nagios') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Netprinter';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Netprinter') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'OI_Ariel';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'OI_Ariel') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'OI_Oberon';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'OI_Oberon') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'OI_Puck';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'OI_Puck') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'OI_Umbriel';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'OI_Umbriel') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'OI_WINSRV';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'OI_WINSRV') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Ofelia';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Ofelia') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Oi_Monsrv';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Oi_Monsrv') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Oi_Mysrv';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Oi_Mysrv') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Oi_PredepSrv';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Oi_PredepSrv') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Oi_Vpnserver01';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Oi_Vpnserver01') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Pollux';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Pollux') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Porcia';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Porcia') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Proteu';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Proteu') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'R1BL08';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'R1BL08') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'R2BL00';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'R2BL00') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'R2BL01';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'R2BL01') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'R2BL02';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'R2BL02') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'R2BL03';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'R2BL03') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'R2BL03';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'R2BL03') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'R2BL03';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'R2BL03') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'R3BL00';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'R3BL00') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'R3BL01';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'R3BL01') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'R3BL02';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'R3BL02') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Reia';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Reia') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Saturno';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Saturno') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Setebos';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Setebos') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Sinope';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Sinope') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Skadi';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Skadi') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Sol';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Sol') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Surtur';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Surtur') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Sycorax';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Sycorax') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'TECHNE_SEEDUCBD';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'TECHNE_SEEDUCBD') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'TECHNE_WEB';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'TECHNE_WEB') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'TRITON';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'TRITON') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Tebe';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Tebe') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Techne_Caronte';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Techne_Caronte') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Techne_Ida';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Techne_Ida') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Techne_Mercurio';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Techne_Mercurio') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Techne_PDC_Atlas';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Techne_PDC_Atlas') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Techne_Plutao';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Techne_Plutao') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Techne_Tarvos';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Techne_Tarvos') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Techne_Tetis';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Techne_Tetis') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Techne_Urano';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Techne_Urano') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Telesto';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Telesto') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Terra';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Terra') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Trinculo';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Trinculo') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'VPNServer';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'VPNServer') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Venus_Fe';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Venus_Fe') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'Xena';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'Xena') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'monitory';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'monitory') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'see_est01';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'see_est01') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'see_est02';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'see_est02') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'see_est03';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'see_est03') and itemtype = 'Computer';
update glpi_computers set entities_id = 1 where name = 'see_srv01';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'see_srv01') and itemtype = 'Computer';
