update glpi_networkequipments set entities_id = 1 where name = 'APCA0502';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'APCA0502') and itemtype = 'NetworkEquipment';
update glpi_networkequipments set entities_id = 1 where name = 'APCA2502';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'APCA2502') and itemtype = 'NetworkEquipment';
update glpi_networkequipments set entities_id = 1 where name = 'APCA2601';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'APCA2601') and itemtype = 'NetworkEquipment';
update glpi_networkequipments set entities_id = 1 where name = 'APCA2801';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'APCA2801') and itemtype = 'NetworkEquipment';
update glpi_networkequipments set entities_id = 1 where name = 'APCA2901';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'APCA2901') and itemtype = 'NetworkEquipment';
update glpi_networkequipments set entities_id = 1 where name = 'APCA3001';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'APCA3001') and itemtype = 'NetworkEquipment';
update glpi_networkequipments set entities_id = 1 where name = 'APCA3002';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'APCA3002') and itemtype = 'NetworkEquipment';
update glpi_networkequipments set entities_id = 1 where name = 'APCM0501';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'APCM0501') and itemtype = 'NetworkEquipment';
update glpi_networkequipments set entities_id = 1 where name = 'APCM0502';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'APCM0502') and itemtype = 'NetworkEquipment';
update glpi_networkequipments set entities_id = 1 where name = 'APCM2501';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'APCM2501') and itemtype = 'NetworkEquipment';
update glpi_networkequipments set entities_id = 1 where name = 'APCM2601';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'APCM2601') and itemtype = 'NetworkEquipment';
update glpi_networkequipments set entities_id = 1 where name = 'APCM2602';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'APCM2602') and itemtype = 'NetworkEquipment';
update glpi_networkequipments set entities_id = 1 where name = 'APCM2801';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'APCM2801') and itemtype = 'NetworkEquipment';
update glpi_networkequipments set entities_id = 1 where name = 'APCM2802';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'APCM2802') and itemtype = 'NetworkEquipment';
update glpi_networkequipments set entities_id = 1 where name = 'APCM2901';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'APCM2901') and itemtype = 'NetworkEquipment';
update glpi_networkequipments set entities_id = 1 where name = 'APCM2902';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'APCM2902') and itemtype = 'NetworkEquipment';
update glpi_networkequipments set entities_id = 1 where name = 'APCM3001';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'APCM3001') and itemtype = 'NetworkEquipment';
update glpi_networkequipments set entities_id = 1 where name = 'APCM3002';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'APCM3002') and itemtype = 'NetworkEquipment';
update glpi_networkequipments set entities_id = 1 where name = 'SWCA0501';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'SWCA0501') and itemtype = 'NetworkEquipment';
update glpi_networkequipments set entities_id = 1 where name = 'SWCA0502';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'SWCA0502') and itemtype = 'NetworkEquipment';
update glpi_networkequipments set entities_id = 1 where name = 'SWCA0701';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'SWCA0701') and itemtype = 'NetworkEquipment';
update glpi_networkequipments set entities_id = 1 where name = 'SWCA2200';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'SWCA2200') and itemtype = 'NetworkEquipment';
update glpi_networkequipments set entities_id = 1 where name = 'SWCA2501';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'SWCA2501') and itemtype = 'NetworkEquipment';
update glpi_networkequipments set entities_id = 1 where name = 'SWCA2502';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'SWCA2502') and itemtype = 'NetworkEquipment';
update glpi_networkequipments set entities_id = 1 where name = 'SWCA2503';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'SWCA2503') and itemtype = 'NetworkEquipment';
update glpi_networkequipments set entities_id = 1 where name = 'SWCA2601';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'SWCA2601') and itemtype = 'NetworkEquipment';
update glpi_networkequipments set entities_id = 1 where name = 'SWCA2602';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'SWCA2602') and itemtype = 'NetworkEquipment';
update glpi_networkequipments set entities_id = 1 where name = 'SWCA2603';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'SWCA2603') and itemtype = 'NetworkEquipment';
update glpi_networkequipments set entities_id = 1 where name = 'SWCA2801';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'SWCA2801') and itemtype = 'NetworkEquipment';
update glpi_networkequipments set entities_id = 1 where name = 'SWCA2802';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'SWCA2802') and itemtype = 'NetworkEquipment';
update glpi_networkequipments set entities_id = 1 where name = 'SWCA2803';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'SWCA2803') and itemtype = 'NetworkEquipment';
update glpi_networkequipments set entities_id = 1 where name = 'SWCA2901';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'SWCA2901') and itemtype = 'NetworkEquipment';
update glpi_networkequipments set entities_id = 1 where name = 'SWCA2902';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'SWCA2902') and itemtype = 'NetworkEquipment';
update glpi_networkequipments set entities_id = 1 where name = 'SWCA3001';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'SWCA3001') and itemtype = 'NetworkEquipment';
update glpi_networkequipments set entities_id = 1 where name = 'SWCA3002';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'SWCA3002') and itemtype = 'NetworkEquipment';
update glpi_networkequipments set entities_id = 1 where name = 'SWCA3003';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'SWCA3003') and itemtype = 'NetworkEquipment';
update glpi_networkequipments set entities_id = 1 where name = 'SWCM0501';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'SWCM0501') and itemtype = 'NetworkEquipment';
update glpi_networkequipments set entities_id = 1 where name = 'SWCM0702';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'SWCM0702') and itemtype = 'NetworkEquipment';
update glpi_networkequipments set entities_id = 1 where name = 'SWCM0703';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'SWCM0703') and itemtype = 'NetworkEquipment';
update glpi_networkequipments set entities_id = 1 where name = 'SWCM2501';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'SWCM2501') and itemtype = 'NetworkEquipment';
update glpi_networkequipments set entities_id = 1 where name = 'SWCM2601';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'SWCM2601') and itemtype = 'NetworkEquipment';
update glpi_networkequipments set entities_id = 1 where name = 'SWCM2602';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'SWCM2602') and itemtype = 'NetworkEquipment';
update glpi_networkequipments set entities_id = 1 where name = 'SWCM2801';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'SWCM2801') and itemtype = 'NetworkEquipment';
update glpi_networkequipments set entities_id = 1 where name = 'SWCM2802';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'SWCM2802') and itemtype = 'NetworkEquipment';
update glpi_networkequipments set entities_id = 1 where name = 'SWCM2901';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'SWCM2901') and itemtype = 'NetworkEquipment';
update glpi_networkequipments set entities_id = 1 where name = 'SWCM2902';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'SWCM2902') and itemtype = 'NetworkEquipment';
update glpi_networkequipments set entities_id = 1 where name = 'SWCM3001';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'SWCM3001') and itemtype = 'NetworkEquipment';
update glpi_networkequipments set entities_id = 1 where name = 'SWCM3002';
update glpi_networkports set entities_id = 1 where items_id = (select id from glpi_computers where name = 'SWCM3002') and itemtype = 'NetworkEquipment';


insert into glpi_computers (itv_key, alias, name, locations_id, computertypes_id, manufacturers_id, groups_id, states_id, entities_id ) select chave, alias, host_name, 1, 2, 38, 2, 1, 1 from itvision_ics_backup where alias in ('R1BL08', 'R2BL00', 'R2BL01', 'R2BL02', 'R2BL03', 'R2BL03', 'R2BL03', 'R3BL00', 'R3BL01', 'R3BL02') and COD_FABRICANTE = 'blade';
insert into glpi_networkports (items_id, itemtype, ip, entities_id ) select c.id, "Computer", b.ip, 1 from itvision_ics_backup b, glpi_computers c where c.itv_key = b.chave and b.alias in ('R1BL08', 'R2BL00', 'R2BL01', 'R2BL02', 'R2BL03', 'R2BL03', 'R2BL03', 'R3BL00', 'R3BL01', 'R3BL02') and b.COD_FABRICANTE = 'blade';


insert into glpi_computers (itv_key, alias, name, computertypes_id, states_id, entities_id ) select chave, alias, host_name, 1, 1, 1 from itvision_ics_backup where alias in ('Censo', 'Centreon', 'Easy', 'Edge-OCS', 'Epmeteu', 'Europa', 'IO', 'Kore', 'Marte', 'Sinope', 'Sol', 'Venus_Fe', 'monitory') ;

insert into glpi_networkports (items_id, itemtype, ip, entities_id ) select c.id, "Computer", b.ip, 1 from itvision_ics_backup b, glpi_computers c where c.itv_key = b.chave and b.alias in ('Censo', 'Centreon', 'Easy', 'Edge-OCS', 'Epmeteu', 'Europa', 'IO', 'Kore', 'Marte', 'Sinope', 'Sol', 'Venus_Fe', 'monitory') ;

insert into glpi_computers (itv_key, alias, name, computertypes_id, states_id, entities_id ) select chave, alias, host_name, 1, 1, 1 from itvision_ics_backup where alias like 'Easy%';

insert into glpi_networkports (items_id, itemtype, ip, entities_id ) select c.id, "Computer", b.ip, 1 from itvision_ics_backup b, glpi_computers c where c.itv_key = b.chave and b.alias like 'Easy%';

