DROP TABLE IF EXISTS `itvision_ics_backup`;

CREATE TABLE `itvision_ics_backup` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `COUNT_UPDATE` int(11) NOT NULL DEFAULT '0',
  `CHAVE` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `SERIAL_NUMBER` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `ALIAS` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `HOST_NAME` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `MAC_ADDRESS` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `IP` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `PATRIMONIO` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `FABRICANTE` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `COD_FABRICANTE` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `MOD_FABRICANTE` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `VERSAO` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `FAMILIA` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `CLASSE` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `GARANTIA` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `LOCALIZACAO` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `USUARIO_RESPONSAVEL` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `INICIO_RESPONSABILIDADE` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `FORNECEDOR` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `LICENCA` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `DATA_COMPRA` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `DATA_ENTRADA` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `STATUS` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `STATUS_AGENDADO` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `CUSTO` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `STATUS_AGENDADO_2` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `CUSTO_2` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `SERVICO` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `AMBIENTE` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `IP_SECUNDARIO` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `IP_TERCIARIO` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `SERVIDOR` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `NOME_DO_SITE` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `CLIENTE` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `EMAIL` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `TELEFONE` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `CELULAR` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `RELEVANCIA` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `CIRCUITO` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
 PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=8 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


