#!/bin/bash

key=$1



IPS=`echo "select ip from itvision_ics_backup where CHAVE like '%$key%';" | mysql -u root --password=itv proderj | grep -v ip`
echo IPS = $IPS
#echo "select ip from itvision_ics_backup where CHAVE like '%$key%';" 

# (locations_id, computermodels_id, computertypes_id, manufacturers_id) VALUES (1, 5, 0, 39)

# insert into glpi_computers 
# set (itv_key, alias, name, entities_id, states_id )
# select chave, alias, host_name, 0, 1 from itvision_ics_backup where chave = '$key';


echo "select id from glpi_computers where itv_key like '%$key%';" | mysql -u root --password=itv proderj
echo "select id from glpi_computers where itv_key like '%$key%';"

# insert into glpi_networkports (items_id, itemtype, entities_id) values select id, "Computer", 0 
# from glpi_computers where computertypes_id = 5;

