INSERT INTO `glpi_manufacturers` VALUES ('1','Checkpoint','');
INSERT INTO `glpi_manufacturers` VALUES ('2','Cisco','');
INSERT INTO `glpi_manufacturers` VALUES ('3','Sun','');
INSERT INTO `glpi_manufacturers` VALUES ('4','Dell','');
INSERT INTO `glpi_manufacturers` VALUES ('5','HP','');
INSERT INTO `glpi_manufacturers` VALUES ('6','IBM','');
INSERT INTO `glpi_manufacturers` VALUES ('7','N/A','');
INSERT INTO `glpi_manufacturers` VALUES ('8','Máquina Montada','');
INSERT INTO `glpi_manufacturers` VALUES ('9','Samsung','');
INSERT INTO `glpi_manufacturers` VALUES ('10','LG','');
INSERT INTO `glpi_manufacturers` VALUES ('11','Philips','');
INSERT INTO `glpi_manufacturers` VALUES ('12','APC','');
INSERT INTO `glpi_manufacturers` VALUES ('13','Apple','');
INSERT INTO `glpi_manufacturers` VALUES ('14','XEROX','');
INSERT INTO `glpi_manufacturers` VALUES ('15','FortiNet','');
INSERT INTO `glpi_manufacturers` VALUES ('16','Elektro','');
INSERT INTO `glpi_manufacturers` VALUES ('17','Konica Minolta','');
INSERT INTO `glpi_manufacturers` VALUES ('18','Vanguard','');
INSERT INTO `glpi_manufacturers` VALUES ('19','Sony','');
INSERT INTO `glpi_manufacturers` VALUES ('20','WANDEL & GOLTERTMANN','');
INSERT INTO `glpi_manufacturers` VALUES ('21','Packteer','');
INSERT INTO `glpi_manufacturers` VALUES ('22','Brother Industries','');
INSERT INTO `glpi_manufacturers` VALUES ('23','LP','');
INSERT INTO `glpi_manufacturers` VALUES ('24','Garmin','');
INSERT INTO `glpi_manufacturers` VALUES ('25','TEKTRONIX','');
INSERT INTO `glpi_manufacturers` VALUES ('26','DLP Projector','');
INSERT INTO `glpi_manufacturers` VALUES ('27','Proteco','');
INSERT INTO `glpi_manufacturers` VALUES ('28','D-Link','');
INSERT INTO `glpi_manufacturers` VALUES ('29','Planet','');
INSERT INTO `glpi_manufacturers` VALUES ('30','Nomadix','');
INSERT INTO `glpi_manufacturers` VALUES ('31','Linksys','');
INSERT INTO `glpi_manufacturers` VALUES ('32','Nokia','');
INSERT INTO `glpi_manufacturers` VALUES ('33','3COM','');
INSERT INTO `glpi_manufacturers` VALUES ('34','BlackBox','');
INSERT INTO `glpi_operatingsystems` VALUES ('1','Linux','');
INSERT INTO `glpi_operatingsystems` VALUES ('2','Mac OS X','');
INSERT INTO `glpi_operatingsystems` VALUES ('3','Windows XP','');
INSERT INTO `glpi_operatingsystems` VALUES ('4','Windows Vista','');
INSERT INTO `glpi_operatingsystems` VALUES ('5','Windows 7','');
INSERT INTO `glpi_operatingsystems` VALUES ('6','IOS','');
INSERT INTO `glpi_operatingsystems` VALUES ('7','Mac OS X Snow Leopard','');
INSERT INTO `glpi_operatingsystems` VALUES ('8','Windows Server 2008 R2 Enterprise','');
INSERT INTO `glpi_operatingsystems` VALUES ('9','Windows 2000 Server','');
INSERT INTO `glpi_operatingsystems` VALUES ('10','Solaris 10','');
INSERT INTO `glpi_dropdown_ram_type` VALUES ('1','EDO',NULL);
INSERT INTO `glpi_dropdown_ram_type` VALUES ('2','DDR',NULL);
INSERT INTO `glpi_dropdown_ram_type` VALUES ('3','SDRAM',NULL);
INSERT INTO `glpi_dropdown_ram_type` VALUES ('4','SDRAM-2',NULL);
INSERT INTO `glpi_dropdown_software_category` VALUES ('1','Serviço WEB','');
INSERT INTO `glpi_dropdown_software_category` VALUES ('2','Cliente-Servidor','');
INSERT INTO `glpi_states` VALUES ('1','Ativo','Item de configuracao em operação normal.');
INSERT INTO `glpi_states` VALUES ('2','Estoque','');
INSERT INTO `glpi_states` VALUES ('3','Defeito','Item de configuração com defeito.');
INSERT INTO `glpi_states` VALUES ('4','Manutenção','');
INSERT INTO `glpi_states` VALUES ('5','Descartado','');
INSERT INTO `glpi_states` VALUES ('6','Desligado','');
INSERT INTO `glpi_taskcategories` VALUES ('1','0','Incidente','Incidente','','1');
INSERT INTO `glpi_taskcategories` VALUES ('190','0','Requisicao de servico','Requisicao de servico','','1');
INSERT INTO `glpi_taskcategories` VALUES ('3','1','Switch','Incidente > Switch','','2');
INSERT INTO `glpi_taskcategories` VALUES ('4','2','Switch','Requisição de Serviço > Switch','','2');
INSERT INTO `glpi_taskcategories` VALUES ('5','1','Roteador','Incidente > Roteador','','2');
INSERT INTO `glpi_taskcategories` VALUES ('6','2','Roteador','Requisição de Serviço > Roteador','','2');
INSERT INTO `glpi_taskcategories` VALUES ('9','1','Telefonia','Incidente > Telefonia','','2');
INSERT INTO `glpi_taskcategories` VALUES ('10','2','Telefonia','Requisição de Serviço > Telefonia','','2');
INSERT INTO `glpi_taskcategories` VALUES ('11','1','Cabeamento','Incidente > Cabeamento','','2');
INSERT INTO `glpi_taskcategories` VALUES ('12','2','Cabeamento','Requisição de Serviço > Cabeamento','','2');
INSERT INTO `glpi_taskcategories` VALUES ('13','1','Video-conferência','Incidente > Video-conferência','','2');
INSERT INTO `glpi_taskcategories` VALUES ('14','2','Video-conferência','Requisição de Serviço > Video-conferência','','2');
INSERT INTO `glpi_taskcategories` VALUES ('16','2','Servidores','Requisição de Serviço > Servidores','','2');
INSERT INTO `glpi_taskcategories` VALUES ('17','1','Servidores','Incidente > Servidores','','2');
INSERT INTO `glpi_taskcategories` VALUES ('19','1','Ar-Condicionado','Incidente > Ar-Condicionado','','2');
INSERT INTO `glpi_taskcategories` VALUES ('20','2','Ar-Condicionado','Requisição de Serviço > Ar-Condicionado','','2');
INSERT INTO `glpi_taskcategories` VALUES ('21','1','No-Break','Incidente > No-Break','','2');
INSERT INTO `glpi_taskcategories` VALUES ('22','2','No-Break','Requisição de Serviço > No-Break','','2');
INSERT INTO `glpi_taskcategories` VALUES ('23','1','Segurança','Incidente > Segurança','','2');
INSERT INTO `glpi_taskcategories` VALUES ('24','2','Segurança','Requisição de Serviço > Segurança','','2');
INSERT INTO `glpi_taskcategories` VALUES ('25','2','Fibra Óptica','Requisição de Serviço > Fibra Óptica','','2');
INSERT INTO `glpi_taskcategories` VALUES ('26','2','Mídia Converter','Requisição de Serviço > Mídia Converter','','2');
INSERT INTO `glpi_taskcategories` VALUES ('27','3','VERIFICAR ERRO NA INTERFACE','Incidente > Switch > VERIFICAR ERRO NA INTERFACE','','3');
INSERT INTO `glpi_taskcategories` VALUES ('28','3','PERDA DE CONEXÃO DE GERÊNCIA','Incidente > Switch > PERDA DE CONEXÃO DE GERÊNCIA','','3');
INSERT INTO `glpi_taskcategories` VALUES ('29','3','INSTABILIDADE','Incidente > Switch > INSTABILIDADE','','3');
INSERT INTO `glpi_taskcategories` VALUES ('30','3','TRAVAMENTO','Incidente > Switch > TRAVAMENTO','','3');
INSERT INTO `glpi_taskcategories` VALUES ('31','3','SEM ALIMENTAÇÃO ELÉTRICA','Incidente > Switch > SEM ALIMENTAÇÃO ELÉTRICA','','3');
INSERT INTO `glpi_taskcategories` VALUES ('32','3','PERDA DE COMUNICAÇÃO','Incidente > Switch > PERDA DE COMUNICAÇÃO','','3');
INSERT INTO `glpi_taskcategories` VALUES ('33','5','VERIFICAR ERRO NA INTERFACE','Incidente > Roteador > VERIFICAR ERRO NA INTERFACE','','3');
INSERT INTO `glpi_taskcategories` VALUES ('34','5','PERDA DE CONEXÃO DE GERÊNCIA','Incidente > Roteador > PERDA DE CONEXÃO DE GERÊNCIA','','3');
INSERT INTO `glpi_taskcategories` VALUES ('35','5','PERDA DE PACOTES','Incidente > Roteador > PERDA DE PACOTES','','3');
INSERT INTO `glpi_taskcategories` VALUES ('36','5','INSTABILIDADE','Incidente > Roteador > INSTABILIDADE','','3');
INSERT INTO `glpi_taskcategories` VALUES ('37','5','TRAVAMENTO','Incidente > Roteador > TRAVAMENTO','','3');
INSERT INTO `glpi_taskcategories` VALUES ('38','5','SEM ALIMENTAÇÃO ELÉTRICA','Incidente > Roteador > SEM ALIMENTAÇÃO ELÉTRICA','','3');
INSERT INTO `glpi_taskcategories` VALUES ('39','5','PERDA DE COMUNICAÇÃO','Incidente > Roteador > PERDA DE COMUNICAÇÃO','','3');
INSERT INTO `glpi_taskcategories` VALUES ('169','164','Falta de fornecimento de energia','Incidente > Wireless > AP > Sem comunicacao > Infra Eletrica > Falta de fornecimento de energia','','6');
INSERT INTO `glpi_taskcategories` VALUES ('170','164','Sobrecarga eletrica','Incidente > Wireless > AP > Sem comunicacao > Infra Eletrica > Sobrecarga eletrica','','6');
INSERT INTO `glpi_taskcategories` VALUES ('171','165','Rompimento back bone','Incidente > Wireless > AP > Sem comunicacao > Infra Fibra Optica > Rompimento back bone','','6');
INSERT INTO `glpi_taskcategories` VALUES ('45','13','INSTABILIDADE','Incidente > Video-conferência > INSTABILIDADE','','3');
INSERT INTO `glpi_taskcategories` VALUES ('46','9','GATEWAY DE VOZ SEM COMUNICAÇÃO','Incidente > Telefonia > GATEWAY DE VOZ SEM COMUNICAÇÃO','','3');
INSERT INTO `glpi_taskcategories` VALUES ('47','4','VERIFICAR IOS','Requisição de Serviço > Switch > VERIFICAR IOS','','3');
INSERT INTO `glpi_taskcategories` VALUES ('48','4','RESERVAR INTERFACE','Requisição de Serviço > Switch > RESERVAR INTERFACE','','3');
INSERT INTO `glpi_taskcategories` VALUES ('49','4','HABILITAR INTERFACE','Requisição de Serviço > Switch > HABILITAR INTERFACE','','3');
INSERT INTO `glpi_taskcategories` VALUES ('50','4','CONFIGURAR INTERFACE','Requisição de Serviço > Switch > CONFIGURAR INTERFACE','','3');
INSERT INTO `glpi_taskcategories` VALUES ('51','4','DESABILTAR INTERFACE','Requisição de Serviço > Switch > DESABILTAR INTERFACE','','3');
INSERT INTO `glpi_taskcategories` VALUES ('52','4','MONITORAR INTERFACE','Requisição de Serviço > Switch > MONITORAR INTERFACE','','3');
INSERT INTO `glpi_taskcategories` VALUES ('53','4','REALOCAR INTERFACE','Requisição de Serviço > Switch > REALOCAR INTERFACE','','3');
INSERT INTO `glpi_taskcategories` VALUES ('54','4','VERIFICAR CONFIGURAÇÃO DE INTERFACE','Requisição de Serviço > Switch > VERIFICAR CONFIGURAÇÃO DE INTERFACE','','3');
INSERT INTO `glpi_taskcategories` VALUES ('55','4','VERIFICAR STATUS DE INTERFACE','Requisição de Serviço > Switch > VERIFICAR STATUS DE INTERFACE','','3');
INSERT INTO `glpi_taskcategories` VALUES ('56','4','HABILITAR ETHERCHANNEL','Requisição de Serviço > Switch > HABILITAR ETHERCHANNEL','','3');
INSERT INTO `glpi_taskcategories` VALUES ('57','4','CONFIGURAR ETHERCHANNEL','Requisição de Serviço > Switch > CONFIGURAR ETHERCHANNEL','','3');
INSERT INTO `glpi_taskcategories` VALUES ('58','4','REMOVER ETHERCHANNEL','Requisição de Serviço > Switch > REMOVER ETHERCHANNEL','','3');
INSERT INTO `glpi_taskcategories` VALUES ('59','4','INSTALAR SWITCH','Requisição de Serviço > Switch > INSTALAR SWITCH','','3');
INSERT INTO `glpi_taskcategories` VALUES ('60','4','CONFIGURAR SWITCH','Requisição de Serviço > Switch > CONFIGURAR SWITCH','','3');
INSERT INTO `glpi_taskcategories` VALUES ('61','4','MONITORAR SWITCH','Requisição de Serviço > Switch > MONITORAR SWITCH','','3');
INSERT INTO `glpi_taskcategories` VALUES ('62','4','Configurar VLAN','Switch > Configurar VLAN','','2');
INSERT INTO `glpi_taskcategories` VALUES ('63','4','INSERIR CONFIGURAÇÃO DE GERÊNCIA','Requisição de Serviço > Switch > INSERIR CONFIGURAÇÃO DE GERÊNCIA','','3');
INSERT INTO `glpi_taskcategories` VALUES ('64','4','VERIFICAR FONTE','Requisição de Serviço > Switch > VERIFICAR FONTE','','3');
INSERT INTO `glpi_taskcategories` VALUES ('65','4','VERIFICAR TEMPERATURA','Requisição de Serviço > Switch > VERIFICAR TEMPERATURA','','3');
INSERT INTO `glpi_taskcategories` VALUES ('66','4','VERIFICAR LINE CORD','Requisição de Serviço > Switch > VERIFICAR LINE CORD','','3');
INSERT INTO `glpi_taskcategories` VALUES ('67','6','VERIFICAR IOS','Requisição de Serviço > Roteador > VERIFICAR IOS','','3');
INSERT INTO `glpi_taskcategories` VALUES ('68','6','CONFIGURAR INTERFACE','Requisição de Serviço > Roteador > CONFIGURAR INTERFACE','','3');
INSERT INTO `glpi_taskcategories` VALUES ('69','6','VERIFICAR CONFIGURAÇÃO DE INTERFACE','Requisição de Serviço > Roteador > VERIFICAR CONFIGURAÇÃO DE INTERFACE','','3');
INSERT INTO `glpi_taskcategories` VALUES ('70','6','VERIFICAR STATUS DE INTERFACE','Requisição de Serviço > Roteador > VERIFICAR STATUS DE INTERFACE','','3');
INSERT INTO `glpi_taskcategories` VALUES ('71','6','INSTALAR ROTEADOR','Requisição de Serviço > Roteador > INSTALAR ROTEADOR','','3');
INSERT INTO `glpi_taskcategories` VALUES ('72','6','CONFIGURAR ROTEADOR','Requisição de Serviço > Roteador > CONFIGURAR ROTEADOR','','3');
INSERT INTO `glpi_taskcategories` VALUES ('73','6','MONITORAR ROTEADOR','Requisição de Serviço > Roteador > MONITORAR ROTEADOR','','3');
INSERT INTO `glpi_taskcategories` VALUES ('74','6','MONITORAR LINK','Requisição de Serviço > Roteador > MONITORAR LINK','','3');
INSERT INTO `glpi_taskcategories` VALUES ('75','6','REALOCAR ROTEADOR','Requisição de Serviço > Roteador > REALOCAR ROTEADOR','','3');
INSERT INTO `glpi_taskcategories` VALUES ('76','6','CRIAR VLAN','Requisição de Serviço > Roteador > CRIAR VLAN','','3');
INSERT INTO `glpi_taskcategories` VALUES ('77','6','INSERIR ROTAS ESTÁTICAS','Requisição de Serviço > Roteador > INSERIR ROTAS ESTÁTICAS','','3');
INSERT INTO `glpi_taskcategories` VALUES ('78','6','REMOVER ROTAS ESTÁTICAS','Requisição de Serviço > Roteador > REMOVER ROTAS ESTÁTICAS','','3');
INSERT INTO `glpi_taskcategories` VALUES ('79','6','INSERIR LISTA DE ACESSO','Requisição de Serviço > Roteador > INSERIR LISTA DE ACESSO','','3');
INSERT INTO `glpi_taskcategories` VALUES ('80','6','REMOVER LISTA DE ACESSO','Requisição de Serviço > Roteador > REMOVER LISTA DE ACESSO','','3');
INSERT INTO `glpi_taskcategories` VALUES ('81','6','INSERIR CONFIGURAÇÃO DE GERÊNCIA','Requisição de Serviço > Roteador > INSERIR CONFIGURAÇÃO DE GERÊNCIA','','3');
INSERT INTO `glpi_taskcategories` VALUES ('82','6','VERIFICAR FONTE','Requisição de Serviço > Roteador > VERIFICAR FONTE','','3');
INSERT INTO `glpi_taskcategories` VALUES ('83','6','VERIFICAR TEMPERATURA','Requisição de Serviço > Roteador > VERIFICAR TEMPERATURA','','3');
INSERT INTO `glpi_taskcategories` VALUES ('84','6','VERIFICAR LINE CORD','Requisição de Serviço > Roteador > VERIFICAR LINE CORD','','3');
INSERT INTO `glpi_taskcategories` VALUES ('85','12','INSERIR CABOS','Requisição de Serviço > Cabeamento > INSERIR CABOS','','3');
INSERT INTO `glpi_taskcategories` VALUES ('86','12','ORGANIZAR CABOS','Requisição de Serviço > Cabeamento > ORGANIZAR CABOS','','3');
INSERT INTO `glpi_taskcategories` VALUES ('87','12','REALOCAR CABOS','Requisição de Serviço > Cabeamento > REALOCAR CABOS','','3');
INSERT INTO `glpi_taskcategories` VALUES ('88','12','DESCONECTAR CABO','Requisição de Serviço > Cabeamento > DESCONECTAR CABO','','3');
INSERT INTO `glpi_taskcategories` VALUES ('89','16','VERIFICAR SISTEMA OPERACIONAL','Requisição de Serviço > Servidores > VERIFICAR SISTEMA OPERACIONAL','','3');
INSERT INTO `glpi_taskcategories` VALUES ('90','16','VERIFICAR SERVIÇOS DO WCS','Requisição de Serviço > Servidores > VERIFICAR SERVIÇOS DO WCS','','3');
INSERT INTO `glpi_taskcategories` VALUES ('91','16','VERIFICAR SERVIÇOS DO ACS','Requisição de Serviço > Servidores > VERIFICAR SERVIÇOS DO ACS','','3');
INSERT INTO `glpi_taskcategories` VALUES ('92','16','VERIFICAR SERVIÇOS DO CISCO WORKS','Requisição de Serviço > Servidores > VERIFICAR SERVIÇOS DO CISCO WORKS','','3');
INSERT INTO `glpi_taskcategories` VALUES ('93','16','VERIFICAR SERVIÇOS DO CALL MANAGER','Requisição de Serviço > Servidores > VERIFICAR SERVIÇOS DO CALL MANAGER','','3');
INSERT INTO `glpi_taskcategories` VALUES ('94','16','VERIFICAR SERVIÇOS DE NAC','Requisição de Serviço > Servidores > VERIFICAR SERVIÇOS DE NAC','','3');
INSERT INTO `glpi_taskcategories` VALUES ('95','16','VERIFICAR INTERFACES','Requisição de Serviço > Servidores > VERIFICAR INTERFACES','','3');
INSERT INTO `glpi_taskcategories` VALUES ('96','16','MIGRAR INTERFACES','Requisição de Serviço > Servidores > MIGRAR INTERFACES','','3');
INSERT INTO `glpi_taskcategories` VALUES ('97','16','VERIFICAR LENTIDÃO','Requisição de Serviço > Servidores > VERIFICAR LENTIDÃO','','3');
INSERT INTO `glpi_taskcategories` VALUES ('168','164','Rompimento cabo eletrico','Incidente > Wireless > AP > Sem comunicacao > Infra Eletrica > Rompimento cabo eletrico','','6');
INSERT INTO `glpi_taskcategories` VALUES ('155','1','Wireless','Incidente > Wireless','','2');
INSERT INTO `glpi_taskcategories` VALUES ('156','155','AP','Incidente > Wireless > AP','','3');
INSERT INTO `glpi_taskcategories` VALUES ('157','155','Controller','Incidente > Wireless > Controller','','3');
INSERT INTO `glpi_taskcategories` VALUES ('166','164','Religamento disjuntor','Incidente > Wireless > AP > Sem comunicacao > Infra Eletrica > Religamento disjuntor','','6');
INSERT INTO `glpi_taskcategories` VALUES ('167','164','Furto cabo eletrico','Incidente > Wireless > AP > Sem comunicacao > Infra Eletrica > Furto cabo eletrico','','6');
INSERT INTO `glpi_taskcategories` VALUES ('104','20','ACOMPANHAR REALOCAÇÃO','Requisição de Serviço > Ar-Condicionado > ACOMPANHAR REALOCAÇÃO','','3');
INSERT INTO `glpi_taskcategories` VALUES ('105','20','ACOMPANHAR INSTALAÇÃO','Requisição de Serviço > Ar-Condicionado > ACOMPANHAR INSTALAÇÃO','','3');
INSERT INTO `glpi_taskcategories` VALUES ('106','26','INSTALAR MIDIA CONVERTER','Requisição de Serviço > Mídia Converter > INSTALAR MIDIA CONVERTER','','3');
INSERT INTO `glpi_taskcategories` VALUES ('107','26','SUBSTITUIR MIDIA CONVERTER','Requisição de Serviço > Mídia Converter > SUBSTITUIR MIDIA CONVERTER','','3');
INSERT INTO `glpi_taskcategories` VALUES ('108','26','VERIFICAR MIDIA CONVERTER','Requisição de Serviço > Mídia Converter > VERIFICAR MIDIA CONVERTER','','3');
INSERT INTO `glpi_taskcategories` VALUES ('109','26','CONFIGURAR MIDIA CONVERTER','Requisição de Serviço > Mídia Converter > CONFIGURAR MIDIA CONVERTER','','3');
INSERT INTO `glpi_taskcategories` VALUES ('110','25','ACOMPANHAR MIGRAÇÃO DE CIRCUITOS','Requisição de Serviço > Fibra Óptica > ACOMPANHAR MIGRAÇÃO DE CIRCUITOS','','3');
INSERT INTO `glpi_taskcategories` VALUES ('111','24','VERIFICAR MODULOS DO ASA','Requisição de Serviço > Segurança > VERIFICAR MODULOS DO ASA','','3');
INSERT INTO `glpi_taskcategories` VALUES ('112','24','VERIFICAR INTERFACES','Requisição de Serviço > Segurança > VERIFICAR INTERFACES','','3');
INSERT INTO `glpi_taskcategories` VALUES ('113','24','VERIFICAR IOS','Requisição de Serviço > Segurança > VERIFICAR IOS','','3');
INSERT INTO `glpi_taskcategories` VALUES ('114','24','CADASTRAR USUARIOS','Requisição de Serviço > Segurança > CADASTRAR USUARIOS','','3');
INSERT INTO `glpi_taskcategories` VALUES ('115','24','CADASTRAR GRUPO DE USUARIOS','Requisição de Serviço > Segurança > CADASTRAR GRUPO DE USUARIOS','','3');
INSERT INTO `glpi_taskcategories` VALUES ('116','24','CONFIGURAR ACESSO AOS USUARIOS','Requisição de Serviço > Segurança > CONFIGURAR ACESSO AOS USUARIOS','','3');
INSERT INTO `glpi_taskcategories` VALUES ('117','24','CONFIGURAR ACESSO A VPN','Requisição de Serviço > Segurança > CONFIGURAR ACESSO A VPN','','3');
INSERT INTO `glpi_taskcategories` VALUES ('118','24','VERIFICAR AS ROTAS ESTATICAS','Requisição de Serviço > Segurança > VERIFICAR AS ROTAS ESTATICAS','','3');
INSERT INTO `glpi_taskcategories` VALUES ('119','24','VERIFICAR O NAT','Requisição de Serviço > Segurança > VERIFICAR O NAT','','3');
INSERT INTO `glpi_taskcategories` VALUES ('120','24','VERIFICAR AS LISTAS DE ACESSO','Requisição de Serviço > Segurança > VERIFICAR AS LISTAS DE ACESSO','','3');
INSERT INTO `glpi_taskcategories` VALUES ('121','24','VERIFICAR O ETHERCHANNEL','Requisição de Serviço > Segurança > VERIFICAR O ETHERCHANNEL','','3');
INSERT INTO `glpi_taskcategories` VALUES ('122','14','TESTAR CONECTIVIDADE','Requisição de Serviço > Video-conferência > TESTAR CONECTIVIDADE','','3');
INSERT INTO `glpi_taskcategories` VALUES ('123','14','CONFIGURAR VIDEO-CONFERENCIA','Requisição de Serviço > Video-conferência > CONFIGURAR VIDEO-CONFERENCIA','','3');
INSERT INTO `glpi_taskcategories` VALUES ('124','14','INSTALAR VIDEO-CONFERENCIA','Requisição de Serviço > Video-conferência > INSTALAR VIDEO-CONFERENCIA','','3');
INSERT INTO `glpi_taskcategories` VALUES ('125','10','CADASTRAR TELEFONES','Requisição de Serviço > Telefonia > CADASTRAR TELEFONES','','3');
INSERT INTO `glpi_taskcategories` VALUES ('126','10','CONFIGURAR ACESSO DE TELEFONE','Requisição de Serviço > Telefonia > CONFIGURAR ACESSO DE TELEFONE','','3');
INSERT INTO `glpi_taskcategories` VALUES ('127','10','CONFIGURAR GRUPO DE TELEFONE','Requisição de Serviço > Telefonia > CONFIGURAR GRUPO DE TELEFONE','','3');
INSERT INTO `glpi_taskcategories` VALUES ('128','10','ALTERAR CONFIGURAÇÃO DE TELEFONE','Requisição de Serviço > Telefonia > ALTERAR CONFIGURAÇÃO DE TELEFONE','','3');
INSERT INTO `glpi_taskcategories` VALUES ('129','10','INSTALAR TELEFONE IP','Requisição de Serviço > Telefonia > INSTALAR TELEFONE IP','','3');
INSERT INTO `glpi_taskcategories` VALUES ('130','10','SUBSTITUIR TELEFONE IP','Requisição de Serviço > Telefonia > SUBSTITUIR TELEFONE IP','','3');
INSERT INTO `glpi_taskcategories` VALUES ('131','10','INSTALAR ATA','Requisição de Serviço > Telefonia > INSTALAR ATA','','3');
INSERT INTO `glpi_taskcategories` VALUES ('132','10','CONFIGURAR ATA','Requisição de Serviço > Telefonia > CONFIGURAR ATA','','3');
INSERT INTO `glpi_taskcategories` VALUES ('133','10','INSTALAR GATEWAY DE VOZ','Requisição de Serviço > Telefonia > INSTALAR GATEWAY DE VOZ','','3');
INSERT INTO `glpi_taskcategories` VALUES ('134','10','CONFIGURAR GATEWAY DE VOZ','Requisição de Serviço > Telefonia > CONFIGURAR GATEWAY DE VOZ','','3');
INSERT INTO `glpi_taskcategories` VALUES ('135','10','VERIFICAR QUALIDADE DE SERVIÇO','Requisição de Serviço > Telefonia > VERIFICAR QUALIDADE DE SERVIÇO','','3');
INSERT INTO `glpi_taskcategories` VALUES ('173','165','Furto cabo optico','Incidente > Wireless > AP > Sem comunicacao > Infra Fibra Optica > Furto cabo optico','','6');
INSERT INTO `glpi_taskcategories` VALUES ('172','165','Rompimento subida poste','Incidente > Wireless > AP > Sem comunicacao > Infra Fibra Optica > Rompimento subida poste','','6');
INSERT INTO `glpi_taskcategories` VALUES ('144','1','LAN','Incidente > LAN','','2');
INSERT INTO `glpi_taskcategories` VALUES ('158','144','Switch','Incidente > LAN > Switch','','3');
INSERT INTO `glpi_taskcategories` VALUES ('159','144','Roteador','Incidente > LAN > Roteador','','3');
INSERT INTO `glpi_taskcategories` VALUES ('147','1','WAN','Incidente > WAN','','2');
INSERT INTO `glpi_taskcategories` VALUES ('160','147','Roteador','Incidente > WAN > Roteador','','3');
INSERT INTO `glpi_taskcategories` VALUES ('161','156','Sem comunicacao','Incidente > Wireless > AP > Sem comunicacao','','4');
INSERT INTO `glpi_taskcategories` VALUES ('162','161','Hardware reset','Incidente > Wireless > AP > Sem comunicacao > Hardware reset','','5');
INSERT INTO `glpi_taskcategories` VALUES ('163','161','Retorno sem intervencao','Incidente > Wireless > AP > Sem comunicacao > Retorno sem intervencao','','5');
INSERT INTO `glpi_taskcategories` VALUES ('164','161','Infra Eletrica','Incidente > Wireless > AP > Sem comunicacao > Infra Eletrica','','5');
INSERT INTO `glpi_taskcategories` VALUES ('165','161','Infra Fibra Optica','Incidente > Wireless > AP > Sem comunicacao > Infra Fibra Optica','','5');
INSERT INTO `glpi_taskcategories` VALUES ('174','157','Re boot','Incidente > Wireless > Controller > Re boot','','4');
INSERT INTO `glpi_taskcategories` VALUES ('175','174','Atualização IOS','Incidente > Wireless > Controller > Re boot > Atualização IOS','','5');
INSERT INTO `glpi_taskcategories` VALUES ('176','158','Sem comunicacao','Incidente > LAN > Switch > Sem comunicacao','','4');
INSERT INTO `glpi_taskcategories` VALUES ('177','176','Infra eletrica','Incidente > LAN > Switch > Sem comunicacao > Infra eletrica','','5');
INSERT INTO `glpi_taskcategories` VALUES ('178','177','Religamento disjuntor','Incidente > LAN > Switch > Sem comunicacao > Infra eletrica > Religamento disjuntor','','6');
INSERT INTO `glpi_taskcategories` VALUES ('179','177','Furto cabo eletrico','Incidente > LAN > Switch > Sem comunicacao > Infra eletrica > Furto cabo eletrico','','6');
INSERT INTO `glpi_taskcategories` VALUES ('180','177','Rompimento cabo eletrico','Incidente > LAN > Switch > Sem comunicacao > Infra eletrica > Rompimento cabo eletrico','','6');
INSERT INTO `glpi_taskcategories` VALUES ('181','177','Falta de fornecimento de energia','Incidente > LAN > Switch > Sem comunicacao > Infra eletrica > Falta de fornecimento de energia','','6');
INSERT INTO `glpi_taskcategories` VALUES ('182','177','Sobrecarga eletrica','Incidente > LAN > Switch > Sem comunicacao > Infra eletrica > Sobrecarga eletrica','','6');
INSERT INTO `glpi_taskcategories` VALUES ('183','176','Infra fibra optica','Incidente > LAN > Switch > Sem comunicacao > Infra fibra optica','','5');
INSERT INTO `glpi_taskcategories` VALUES ('184','183','Rompimento back bone','Incidente > LAN > Switch > Sem comunicacao > Infra fibra optica > Rompimento back bone','','6');
INSERT INTO `glpi_taskcategories` VALUES ('185','183','Rompimento subida poste','Incidente > LAN > Switch > Sem comunicacao > Infra fibra optica > Rompimento subida poste','','6');
INSERT INTO `glpi_taskcategories` VALUES ('186','183','Furto cabo optico','Incidente > LAN > Switch > Sem comunicacao > Infra fibra optica > Furto cabo optico','','6');
INSERT INTO `glpi_taskcategories` VALUES ('187','159','Sem comunicacao','Incidente > LAN > Roteador > Sem comunicacao','','4');
INSERT INTO `glpi_taskcategories` VALUES ('188','187','Infra eletrica','Incidente > LAN > Roteador > Sem comunicacao > Infra eletrica','','5');
INSERT INTO `glpi_taskcategories` VALUES ('189','160','Falta de comunicacao com provedor','Incidente > WAN > Roteador > Falta de comunicacao com provedor','','4');
INSERT INTO `glpi_taskcategories` VALUES ('191','190','Wireless','Requisicao de servico > Wireless','','2');
INSERT INTO `glpi_taskcategories` VALUES ('192','191','Controller','Requisicao de servico > Wireless > Controller','','3');
INSERT INTO `glpi_taskcategories` VALUES ('193','191','Cadastramento de usuario','Requisicao de servico > Wireless > Cadastramento de usuario','','3');
INSERT INTO `glpi_taskcategories` VALUES ('194','192','Atualizacao IOS','Requisicao de servico > Wireless > Controller > Atualizacao IOS','','4');
INSERT INTO `glpi_taskcategories` VALUES ('195','161','Fonte de Alimentacao','Incidente > Wireless > AP > Sem comunicacao > Fonte de Alimentacao','','5');
INSERT INTO `glpi_taskcategories` VALUES ('196','161','Interface 802.11a','Incidente > Wireless > AP > Sem comunicacao > Interface 802.11a','','5');
INSERT INTO `glpi_taskcategories` VALUES ('197','161','Interfarce 802.11b/g','Incidente > Wireless > AP > Sem comunicacao > Interfarce 802.11b/g','','5');
INSERT INTO `glpi_taskcategories` VALUES ('198','161','Reinstalacao de IOS','Incidente > Wireless > AP > Sem comunicacao > Reinstalacao de IOS','','5');
INSERT INTO `glpi_taskcategories` VALUES ('199','0','Problema','Problema','','1');
INSERT INTO `glpi_taskcategories` VALUES ('200','0','Wireless','Wireless','','1');
INSERT INTO `glpi_taskcategories` VALUES ('201','199','Wireless','Problema > Wireless','','2');
INSERT INTO `glpi_taskcategories` VALUES ('205','203','Sem comunicacao','Problema > Wireless > AP > Sem comunicacao','','4');
INSERT INTO `glpi_taskcategories` VALUES ('203','201','AP','Problema > Wireless > AP','','3');
INSERT INTO `glpi_taskcategories` VALUES ('206','205','Intermitencia no servico','Problema > Wireless > AP > Sem comunicacao > Intermitencia no servico','','5');
INSERT INTO `glpi_taskcategories` VALUES ('210','190','Impressora','Requisicao de servico > Impressora','','2');
INSERT INTO `glpi_taskcategories` VALUES ('211','210','Instalação','Requisicao de servico > Impressora > Instalação','','3');
INSERT INTO `glpi_taskcategories` VALUES ('212','190','Computador','Requisicao de servico > Computador','','2');
INSERT INTO `glpi_taskcategories` VALUES ('218','217','Mac','Requisicao de servico > Computador > Desktop > Mac','','4');
INSERT INTO `glpi_taskcategories` VALUES ('214','212','Notebook','Requisicao de servico > Computador > Notebook','','3');
INSERT INTO `glpi_taskcategories` VALUES ('219','217','PC','Requisicao de servico > Computador > Desktop > PC','','4');
INSERT INTO `glpi_taskcategories` VALUES ('217','212','Desktop','Requisicao de servico > Computador > Desktop','','3');
INSERT INTO `glpi_taskcategories` VALUES ('220','214','Mac','Requisicao de servico > Computador > Notebook > Mac','','4');
INSERT INTO `glpi_taskcategories` VALUES ('221','214','PC','Requisicao de servico > Computador > Notebook > PC','','4');
INSERT INTO `glpi_taskcategories` VALUES ('222','218','Instalação','Requisicao de servico > Computador > Desktop > Mac > Instalação','','5');
INSERT INTO `glpi_taskcategories` VALUES ('223','220','Instalação','Requisicao de servico > Computador > Notebook > Mac > Instalação','','5');
INSERT INTO `glpi_taskcategories` VALUES ('224','219','Instalação','Requisicao de servico > Computador > Desktop > PC > Instalação','','5');
INSERT INTO `glpi_taskcategories` VALUES ('225','221','Instalação','Requisicao de servico > Computador > Notebook > PC > Instalação','','5');
INSERT INTO `glpi_taskcategories` VALUES ('226','218','Reinstalação','Requisicao de servico > Computador > Desktop > Mac > Reinstalação','','5');
INSERT INTO `glpi_taskcategories` VALUES ('227','220','Reinstalação','Requisicao de servico > Computador > Notebook > Mac > Reinstalação','','5');
INSERT INTO `glpi_taskcategories` VALUES ('228','219','Reinstalação','Requisicao de servico > Computador > Desktop > PC > Reinstalação','','5');
INSERT INTO `glpi_taskcategories` VALUES ('229','221','Reinstalação','Requisicao de servico > Computador > Notebook > PC > Reinstalação','','5');
INSERT INTO `glpi_taskcategories` VALUES ('230','218','Suporte','Requisicao de servico > Computador > Desktop > Mac > Suporte','','5');
INSERT INTO `glpi_taskcategories` VALUES ('231','220','Suporte','Requisicao de servico > Computador > Notebook > Mac > Suporte','','5');
INSERT INTO `glpi_taskcategories` VALUES ('232','219','Suporte','Requisicao de servico > Computador > Desktop > PC > Suporte','','5');
INSERT INTO `glpi_taskcategories` VALUES ('233','221','Suporte','Requisicao de servico > Computador > Notebook > PC > Suporte','','5');
INSERT INTO `glpi_taskcategories` VALUES ('234','190','Solicitação de Compra','Requisicao de servico > Solicitação de Compra','','2');
INSERT INTO `glpi_taskcategories` VALUES ('235','234','Insumo','Requisicao de servico > Solicitação de Compra > Insumo','','3');
INSERT INTO `glpi_taskcategories` VALUES ('236','235','Lampada Projetor','Requisicao de servico > Solicitação de Compra > Insumo > Lampada Projetor','','4');
INSERT INTO `glpi_taskcategories` VALUES ('237','234','Equipamento','Requisicao de servico > Solicitação de Compra > Equipamento','','3');
INSERT INTO `glpi_taskcategories` VALUES ('238','190','IPCC','Requisicao de servico > IPCC','','2');
INSERT INTO `glpi_taskcategories` VALUES ('239','238','Configuração de Contact Center','Requisicao de servico > IPCC > Configuração de Contact Center','','3');
INSERT INTO `glpi_taskcategories` VALUES ('240','237','Camera','Requisicao de servico > Solicitação de Compra > Equipamento > Camera','','4');
INSERT INTO `glpi_taskcategories` VALUES ('241','190','E-mail','Requisicao de servico > E-mail','','2');
INSERT INTO `glpi_taskcategories` VALUES ('247','234','Conectorização','Requisicao de servico > Solicitação de Compra > Conectorização','','3');
INSERT INTO `glpi_taskcategories` VALUES ('246','242','Usuário Windows','Requisicao de servico > E-mail > Assinatura > Usuário Windows','','4');
INSERT INTO `glpi_taskcategories` VALUES ('245','242','Usuário MAC','Requisicao de servico > E-mail > Assinatura > Usuário MAC','','4');
INSERT INTO `glpi_taskcategories` VALUES ('248','247','Path Cord','Requisicao de servico > Solicitação de Compra > Conectorização > Path Cord','','4');
INSERT INTO `glpi_taskcategories` VALUES ('249','190','Conectorização','Requisicao de servico > Conectorização','','2');
INSERT INTO `glpi_taskcategories` VALUES ('250','249','Instalação','Requisicao de servico > Conectorização > Instalação','','3');
INSERT INTO `glpi_taskcategories` VALUES ('251','250','Path Cord','Requisicao de servico > Conectorização > Instalação > Path Cord','','4');
INSERT INTO `glpi_taskcategories` VALUES ('252','190','Colaboração','Requisicao de servico > Colaboração','','2');
INSERT INTO `glpi_taskcategories` VALUES ('253','252','Integração Agendas','Requisicao de servico > Colaboração > Integração Agendas','','3');
INSERT INTO `glpi_taskcategories` VALUES ('254','253','Usuário MAC','Requisicao de servico > Colaboração > Integração Agendas > Usuário MAC','','4');
INSERT INTO `glpi_taskcategories` VALUES ('255','253','Usuário Windows','Requisicao de servico > Colaboração > Integração Agendas > Usuário Windows','','4');
INSERT INTO `glpi_taskcategories` VALUES ('256','190','Telefonia IP','Requisicao de servico > Telefonia IP','','2');
INSERT INTO `glpi_taskcategories` VALUES ('257','252','Telefonia IP','Requisicao de servico > Colaboração > Telefonia IP','','3');
INSERT INTO `glpi_taskcategories` VALUES ('259','0','Telefonia','Telefonia','','1');
INSERT INTO `glpi_taskcategories` VALUES ('260','257','Funcionalidade Voice Mail','Requisicao de servico > Colaboração > Telefonia IP > Funcionalidade Voice Mail','','4');
INSERT INTO `glpi_taskcategories` VALUES ('261','257','Funcionalidade Chefe - Secretária','Requisicao de servico > Colaboração > Telefonia IP > Funcionalidade Chefe - Secretária','','4');
INSERT INTO `glpi_taskcategories` VALUES ('262','190','LAN','Requisicao de servico > LAN','','2');
INSERT INTO `glpi_taskcategories` VALUES ('263','262','Acesso ao Domínio','Requisicao de servico > LAN > Acesso ao Domínio','','3');
INSERT INTO `glpi_taskcategories` VALUES ('264','263','Senha de acesso','Requisicao de servico > LAN > Acesso ao Domínio > Senha de acesso','','4');
INSERT INTO `glpi_taskcategories` VALUES ('265','262','Acesso Rede Corporativa','Requisicao de servico > LAN > Acesso Rede Corporativa','','3');
INSERT INTO `glpi_taskcategories` VALUES ('267','265','Acesso ao Servidor de Arquivos','Requisicao de servico > LAN > Acesso Rede Corporativa > Acesso ao Servidor de Arquivos','','4');
INSERT INTO `glpi_taskcategories` VALUES ('268','252','Smartphone','Requisicao de servico > Colaboração > Smartphone','','3');
INSERT INTO `glpi_taskcategories` VALUES ('269','268','Configuração Dados','Requisicao de servico > Colaboração > Smartphone > Configuração Dados','','4');
INSERT INTO `glpi_taskcategories` VALUES ('270','190','Endpoint','Requisicao de servico > Endpoint','','2');
INSERT INTO `glpi_taskcategories` VALUES ('271','270','Sistema Operacional','Requisicao de servico > Endpoint > Sistema Operacional','','3');
INSERT INTO `glpi_taskcategories` VALUES ('272','271','Cópia Não Genuína','Requisicao de servico > Endpoint > Sistema Operacional > Cópia Não Genuína','','4');
INSERT INTO `glpi_taskcategories` VALUES ('273','256','Cadastro de senha','Requisicao de servico > Telefonia IP > Cadastro de senha','','3');
INSERT INTO `glpi_taskcategories` VALUES ('274','273','Ligações Externas','Requisicao de servico > Telefonia IP > Cadastro de senha > Ligações Externas','','4');
INSERT INTO `glpi_taskcategories` VALUES ('275','262','Servidor de Arquivos','Requisicao de servico > LAN > Servidor de Arquivos','','3');
INSERT INTO `glpi_taskcategories` VALUES ('276','275','Permissões de pastas','Requisicao de servico > LAN > Servidor de Arquivos > Permissões de pastas','','4');
INSERT INTO `glpi_taskcategories` VALUES ('277','270','Instalação de Software','Requisicao de servico > Endpoint > Instalação de Software','','3');
INSERT INTO `glpi_taskcategories` VALUES ('278','277','Usuário MAC','Requisicao de servico > Endpoint > Instalação de Software > Usuário MAC','','4');
INSERT INTO `glpi_taskcategories` VALUES ('279','277','Usuário Windows','Requisicao de servico > Endpoint > Instalação de Software > Usuário Windows','','4');
INSERT INTO `glpi_taskcategories` VALUES ('280','270','Impressora','Requisicao de servico > Endpoint > Impressora','','3');
INSERT INTO `glpi_taskcategories` VALUES ('281','280','Instalação','Requisicao de servico > Endpoint > Impressora > Instalação','','4');
INSERT INTO `glpi_taskcategories` VALUES ('282','280','Dificuldades de Impressão','Requisicao de servico > Endpoint > Impressora > Dificuldades de Impressão','','4');
INSERT INTO `glpi_taskcategories` VALUES ('283','282','Retorno sem intervencao','Requisicao de servico > Endpoint > Impressora > Dificuldades de Impressão > Retorno sem intervencao','','5');
INSERT INTO `glpi_taskcategories` VALUES ('284','241','Acesso','Requisicao de servico > E-mail > Acesso','','3');
INSERT INTO `glpi_taskcategories` VALUES ('285','284','Retorno sem Intervenção','Requisicao de servico > E-mail > Acesso > Retorno sem Intervenção','','4');
INSERT INTO `glpi_taskcategories` VALUES ('286','190','Projeção de Imagem','Requisicao de servico > Projeção de Imagem','','2');
INSERT INTO `glpi_taskcategories` VALUES ('287','286','Instalação','Requisicao de servico > Projeção de Imagem > Instalação','','3');
INSERT INTO `glpi_taskcategories` VALUES ('288','286','Projetor','Requisicao de servico > Projeção de Imagem > Projetor','','3');
INSERT INTO `glpi_taskcategories` VALUES ('289','288','Reposição de lâmpada','Requisicao de servico > Projeção de Imagem > Projetor > Reposição de lâmpada','','4');
INSERT INTO `glpi_taskcategories` VALUES ('290','271','Instalação','Requisicao de servico > Endpoint > Sistema Operacional > Instalação','','4');
INSERT INTO `glpi_taskcategories` VALUES ('291','288','Instalação','Requisicao de servico > Projeção de Imagem > Projetor > Instalação','','4');
INSERT INTO `glpi_taskcategories` VALUES ('292','241','Webmail Verto','Requisicao de servico > E-mail > Webmail Verto','','3');
INSERT INTO `glpi_taskcategories` VALUES ('293','292','Reset de senha','Requisicao de servico > E-mail > Webmail Verto > Reset de senha','','4');
INSERT INTO `glpi_taskcategories` VALUES ('294','263','Conta de usuário','Requisicao de servico > LAN > Acesso ao Domínio > Conta de usuário','','4');
INSERT INTO `glpi_taskcategories` VALUES ('295','190','WAN','Requisicao de servico > WAN','','2');
INSERT INTO `glpi_taskcategories` VALUES ('296','295','Enlace de Dados','Requisicao de servico > WAN > Enlace de Dados','','3');
INSERT INTO `glpi_taskcategories` VALUES ('297','296','Interrupção de serviço','Requisicao de servico > WAN > Enlace de Dados > Interrupção de serviço','','4');
INSERT INTO `glpi_taskcategories` VALUES ('298','252','Celular','Requisicao de servico > Colaboração > Celular','','3');
INSERT INTO `glpi_taskcategories` VALUES ('299','298','Chamadas','Requisicao de servico > Colaboração > Celular > Chamadas','','4');
INSERT INTO `glpi_taskcategories` VALUES ('300','270','Windows','Requisicao de servico > Endpoint > Windows','','3');
INSERT INTO `glpi_taskcategories` VALUES ('301','300','Sistema Operacional','Requisicao de servico > Endpoint > Windows > Sistema Operacional','','4');
INSERT INTO `glpi_taskcategories` VALUES ('302','301','Instalação','Requisicao de servico > Endpoint > Windows > Sistema Operacional > Instalação','','5');
INSERT INTO `glpi_taskcategories` VALUES ('303','301','Cópia Não-Genuína','Requisicao de servico > Endpoint > Windows > Sistema Operacional > Cópia Não-Genuína','','5');
INSERT INTO `glpi_taskcategories` VALUES ('304','300','Software','Requisicao de servico > Endpoint > Windows > Software','','4');
INSERT INTO `glpi_taskcategories` VALUES ('305','304','Instalação','Requisicao de servico > Endpoint > Windows > Software > Instalação','','5');
INSERT INTO `glpi_taskcategories` VALUES ('306','300','Impressora','Requisicao de servico > Endpoint > Windows > Impressora','','4');
INSERT INTO `glpi_taskcategories` VALUES ('307','306','Instalação','Requisicao de servico > Endpoint > Windows > Impressora > Instalação','','5');
INSERT INTO `glpi_taskcategories` VALUES ('308','306','Dificuldades de Impressão','Requisicao de servico > Endpoint > Windows > Impressora > Dificuldades de Impressão','','5');
INSERT INTO `glpi_taskcategories` VALUES ('309','270','MAC','Requisicao de servico > Endpoint > MAC','','3');
INSERT INTO `glpi_taskcategories` VALUES ('310','309','Sistema Operacional','Requisicao de servico > Endpoint > MAC > Sistema Operacional','','4');
INSERT INTO `glpi_taskcategories` VALUES ('311','310','Instalação','Requisicao de servico > Endpoint > MAC > Sistema Operacional > Instalação','','5');
INSERT INTO `glpi_taskcategories` VALUES ('312','309','Software','Requisicao de servico > Endpoint > MAC > Software','','4');
INSERT INTO `glpi_taskcategories` VALUES ('313','312','Instalação','Requisicao de servico > Endpoint > MAC > Software > Instalação','','5');
INSERT INTO `glpi_taskcategories` VALUES ('314','309','Impressora','Requisicao de servico > Endpoint > MAC > Impressora','','4');
INSERT INTO `glpi_taskcategories` VALUES ('315','314','Instalação','Requisicao de servico > Endpoint > MAC > Impressora > Instalação','','5');
INSERT INTO `glpi_taskcategories` VALUES ('316','314','Dificuldades de Impressão','Requisicao de servico > Endpoint > MAC > Impressora > Dificuldades de Impressão','','5');
INSERT INTO `glpi_taskcategories` VALUES ('317','156','Infra Elétrica','Incidente > Wireless > AP > Infra Elétrica','','4');
INSERT INTO `glpi_taskcategories` VALUES ('318','317','Reparo','Incidente > Wireless > AP > Infra Elétrica > Reparo','','5');
INSERT INTO `glpi_taskcategories` VALUES ('319','241','Criação de Conta','Requisicao de servico > E-mail > Criação de Conta','','3');
INSERT INTO `glpi_taskcategories` VALUES ('320','241','Desabilitar Conta','Requisicao de servico > E-mail > Desabilitar Conta','','3');
INSERT INTO `glpi_taskcategories` VALUES ('321','256','Ligações','Requisicao de servico > Telefonia IP > Ligações','','3');
INSERT INTO `glpi_taskcategories` VALUES ('322','321','Intermitência','Requisicao de servico > Telefonia IP > Ligações > Intermitência','','4');
INSERT INTO `glpi_taskcategories` VALUES ('323','1','E-mail','Incidente > E-mail','','2');
INSERT INTO `glpi_taskcategories` VALUES ('324','323','Não envia mensagem','Incidente > E-mail > Não envia mensagem','','3');
INSERT INTO `glpi_taskcategories` VALUES ('325','257','Conferência','Requisicao de servico > Colaboração > Telefonia IP > Conferência','','4');
INSERT INTO `glpi_taskcategories` VALUES ('326','1','End Point','Incidente > End Point','','2');
INSERT INTO `glpi_taskcategories` VALUES ('327','326','Impressora','Incidente > End Point > Impressora','','3');
INSERT INTO `glpi_taskcategories` VALUES ('328','327','Dificuldades de Impressão','Incidente > End Point > Impressora > Dificuldades de Impressão','','4');
INSERT INTO `glpi_taskcategories` VALUES ('329','1','Endpoint','Incidente > Endpoint','','2');
INSERT INTO `glpi_taskcategories` VALUES ('330','326','Acesso a Internet','Incidente > End Point > Acesso a Internet','','3');
INSERT INTO `glpi_taskcategories` VALUES ('331','330','Restrição de Acesso','Incidente > End Point > Acesso a Internet > Restrição de Acesso','','4');
INSERT INTO `glpi_taskcategories` VALUES ('332','298','Configuração','Requisicao de servico > Colaboração > Celular > Configuração','','4');
INSERT INTO `glpi_taskcategories` VALUES ('333','270','Remanejamento de equipamento','Requisicao de servico > Endpoint > Remanejamento de equipamento','','3');
INSERT INTO `glpi_taskcategories` VALUES ('334','321','Desvio de chamada','Requisicao de servico > Telefonia IP > Ligações > Desvio de chamada','','4');
INSERT INTO `glpi_taskcategories` VALUES ('335','295','Endereçamento','Requisicao de servico > WAN > Endereçamento','','3');
INSERT INTO `glpi_taskcategories` VALUES ('336','190','Equipamento','Requisicao de servico > Equipamento','','2');
INSERT INTO `glpi_taskcategories` VALUES ('337','336','Rack','Requisicao de servico > Equipamento > Rack','','3');
INSERT INTO `glpi_taskcategories` VALUES ('338','337','Instalação','Requisicao de servico > Equipamento > Rack > Instalação','','4');
INSERT INTO `glpi_taskcategories` VALUES ('339','323','Anexos','Incidente > E-mail > Anexos','','3');
INSERT INTO `glpi_taskcategories` VALUES ('340','191','AP','Requisicao de servico > Wireless > AP','','3');
INSERT INTO `glpi_taskcategories` VALUES ('341','156','Substituição','Incidente > Wireless > AP > Substituição','','4');
INSERT INTO `glpi_taskcategories` VALUES ('342','330','Navegação Web','Incidente > End Point > Acesso a Internet > Navegação Web','','4');
INSERT INTO `glpi_taskcategories` VALUES ('343','161','Intermitencia no servico','Incidente > Wireless > AP > Sem comunicacao > Intermitencia no servico','','5');
INSERT INTO `glpi_taskcategories` VALUES ('344','329','PC','Incidente > Endpoint > PC','','3');
INSERT INTO `glpi_taskcategories` VALUES ('345','344','Mal funcionamento','Incidente > Endpoint > PC > Mal funcionamento','','4');
INSERT INTO `glpi_taskcategories` VALUES ('346','241','Configurações','Requisicao de servico > E-mail > Configurações','','3');
INSERT INTO `glpi_taskcategories` VALUES ('347','252','Service Desk','Requisicao de servico > Colaboração > Service Desk','','3');
INSERT INTO `glpi_taskcategories` VALUES ('348','347','Relatório','Requisicao de servico > Colaboração > Service Desk > Relatório','','4');
INSERT INTO `glpi_taskcategories` VALUES ('349','336','AP','Requisicao de servico > Equipamento > AP','','3');
INSERT INTO `glpi_taskcategories` VALUES ('350','349','Substituição','Requisicao de servico > Equipamento > AP > Substituição','','4');
INSERT INTO `glpi_taskcategories` VALUES ('351','294','Exclusão','Requisicao de servico > LAN > Acesso ao Domínio > Conta de usuário > Exclusão','','5');
INSERT INTO `glpi_taskcategories` VALUES ('352','191','Modem','Requisicao de servico > Wireless > Modem','','3');
INSERT INTO `glpi_taskcategories` VALUES ('353','352','Instalação','Requisicao de servico > Wireless > Modem > Instalação','','4');
INSERT INTO `glpi_taskcategories` VALUES ('354','256','Instalação','Requisicao de servico > Telefonia IP > Instalação','','3');
INSERT INTO `glpi_taskcategories` VALUES ('355','347','Demonstrar funcionalidades','Requisicao de servico > Colaboração > Service Desk > Demonstrar funcionalidades','','4');
INSERT INTO `glpi_taskcategories` VALUES ('356','326','Antivírus','Incidente > End Point > Antivírus','','3');
INSERT INTO `glpi_taskcategories` VALUES ('357','326','Software','Incidente > End Point > Software','','3');
INSERT INTO `glpi_taskcategories` VALUES ('358','357','Mal funcionamento','Incidente > End Point > Software > Mal funcionamento','','4');
INSERT INTO `glpi_taskcategories` VALUES ('359','326','Suporte','Incidente > End Point > Suporte','','3');
INSERT INTO `glpi_taskcategories` VALUES ('360','144','Servidor','Incidente > LAN > Servidor','','3');
INSERT INTO `glpi_taskcategories` VALUES ('361','360','Interrupção de serviço','Incidente > LAN > Servidor > Interrupção de serviço','','4');
INSERT INTO `glpi_taskcategories` VALUES ('362','191','Acesso','Requisicao de servico > Wireless > Acesso','','3');
INSERT INTO `glpi_taskcategories` VALUES ('363','362','VertoUser','Requisicao de servico > Wireless > Acesso > VertoUser','','4');
INSERT INTO `glpi_taskcategories` VALUES ('364','362','VertoGuest','Requisicao de servico > Wireless > Acesso > VertoGuest','','4');
INSERT INTO `glpi_taskcategories` VALUES ('365','362','VertoNOC','Requisicao de servico > Wireless > Acesso > VertoNOC','','4');
INSERT INTO `glpi_taskcategories` VALUES ('366','275','Backup','Requisicao de servico > LAN > Servidor de Arquivos > Backup','','4');
INSERT INTO `glpi_taskcategories` VALUES ('367','270','Inventário','Requisicao de servico > Endpoint > Inventário','','3');
INSERT INTO `glpi_taskcategories` VALUES ('368','270','Gerenciamento de mudanças','Requisicao de servico > Endpoint > Gerenciamento de mudanças','','3');
INSERT INTO `glpi_taskcategories` VALUES ('369','317','Instalação de Aterramento','Incidente > Wireless > AP > Infra Elétrica > Instalação de Aterramento','','5');
INSERT INTO `glpi_taskcategories` VALUES ('370','317','Instalacao de Caixa de Proteção','Incidente > Wireless > AP > Infra Elétrica > Instalacao de Caixa de Proteção','','5');
INSERT INTO `glpi_taskcategories` VALUES ('371','263','VLAN','Requisicao de servico > LAN > Acesso ao Domínio > VLAN','','4');
INSERT INTO `glpi_taskcategories` VALUES ('372','190','Monitoramento','Requisicao de servico > Monitoramento','','2');
INSERT INTO `glpi_taskcategories` VALUES ('373','372','ITVision','Requisicao de servico > Monitoramento > ITVision','','3');
INSERT INTO `glpi_taskcategories` VALUES ('374','373','Inclusão de IC\'s','Requisicao de servico > Monitoramento > ITVision > Inclusão de IC\'s','','4');
INSERT INTO `glpi_taskcategories` VALUES ('375','373','Alteração de IC\'s','Requisicao de servico > Monitoramento > ITVision > Alteração de IC\'s','','4');
INSERT INTO `glpi_taskcategories` VALUES ('376','373','Alteração de Relacionamentos','Requisicao de servico > Monitoramento > ITVision > Alteração de Relacionamentos','','4');
INSERT INTO `glpi_taskcategories` VALUES ('377','211','Toner','Requisicao de servico > Impressora > Instalação > Toner','','4');
INSERT INTO `glpi_taskcategories` VALUES ('378','1','Monitoramento','Incidente > Monitoramento','','2');
INSERT INTO `glpi_taskcategories` VALUES ('379','378','ITVision','Incidente > Monitoramento > ITVision','','3');
INSERT INTO `glpi_taskcategories` VALUES ('380','379','Erro','Incidente > Monitoramento > ITVision > Erro','','4');
INSERT INTO `glpi_taskcategories` VALUES ('381','144','Servidor de Arquivos','Incidente > LAN > Servidor de Arquivos','','3');
INSERT INTO `glpi_taskcategories` VALUES ('382','381','Sem acesso','Incidente > LAN > Servidor de Arquivos > Sem acesso','','4');
INSERT INTO `glpi_taskcategories` VALUES ('383','373','Exclusão de IC\'s','Requisicao de servico > Monitoramento > ITVision > Exclusão de IC\'s','','4');
INSERT INTO `glpi_taskcategories` VALUES ('385','317','Sobrecarga de energia','Incidente > Wireless > AP > Infra Elétrica > Sobrecarga de energia','','5');
INSERT INTO `glpi_taskcategories` VALUES ('386','192','Logs','Requisicao de servico > Wireless > Controller > Logs','','4');
INSERT INTO `glpi_taskcategories` VALUES ('387','191','Aterramento','Requisicao de servico > Wireless > Aterramento','','3');
INSERT INTO `glpi_taskcategories` VALUES ('388','387','Instalação','Requisicao de servico > Wireless > Aterramento > Instalação','','4');
INSERT INTO `glpi_taskcategories` VALUES ('389','191','Infra Elétrica','Requisicao de servico > Wireless > Infra Elétrica','','3');
INSERT INTO `glpi_taskcategories` VALUES ('390','389','Instalação','Requisicao de servico > Wireless > Infra Elétrica > Instalação','','4');
INSERT INTO `glpi_taskcategories` VALUES ('391','241','Recuperação de e-mail','Requisicao de servico > E-mail > Recuperação de e-mail','','3');
INSERT INTO `glpi_dropdown_user_types` VALUES ('1','Engenheiro de Campo','');
INSERT INTO `glpi_dropdown_user_types` VALUES ('2','Analista de Suporte','');
INSERT INTO `glpi_dropdown_user_types` VALUES ('3','Cliente','');
INSERT INTO `glpi_dropdown_user_types` VALUES ('4','Usuario','');
INSERT INTO `glpi_dropdown_user_types` VALUES ('5','Presidência','');
INSERT INTO `glpi_computertypes` VALUES ('1','Servidor','');
INSERT INTO `glpi_computertypes` VALUES ('2','Blade','');
INSERT INTO `glpi_computertypes` VALUES ('3','Desktop','');
INSERT INTO `glpi_computertypes` VALUES ('4','Laptop','');
INSERT INTO `glpi_networkequipmenttypes` VALUES ('1','Firewall','');
INSERT INTO `glpi_networkequipmenttypes` VALUES ('2','Switch','');
INSERT INTO `glpi_networkequipmenttypes` VALUES ('3','Roteador','');
INSERT INTO `glpi_networkequipmenttypes` VALUES ('4','Switch Fibre Channel','');
INSERT INTO `glpi_networkequipmenttypes` VALUES ('5','Access Point','');
INSERT INTO `glpi_networkequipmenttypes` VALUES ('6','Controladora Wireless','');
INSERT INTO `glpi_networkequipmenttypes` VALUES ('7','Enlace de Dados','');
INSERT INTO `glpi_networkequipmenttypes` VALUES ('8','Controller','');
INSERT INTO `glpi_networkequipmenttypes` VALUES ('9','Antena para Acess Point','');
INSERT INTO `glpi_networkequipmenttypes` VALUES ('10','Adaptador Telefônico Analógico','');
INSERT INTO `glpi_networkequipmenttypes` VALUES ('11','Analisador de Rede','');
INSERT INTO `glpi_networkequipmenttypes` VALUES ('12','Power Injector','');
INSERT INTO `glpi_networkequipmenttypes` VALUES ('13','Appliance de Autenticação','');
INSERT INTO `glpi_networkequipmenttypes` VALUES ('14','Appliance de Localização','');
INSERT INTO `glpi_networkequipmenttypes` VALUES ('15','Storage','');
INSERT INTO `glpi_networkequipmenttypes` VALUES ('16','HBA','');
INSERT INTO `glpi_networkequipmenttypes` VALUES ('17','IP Camera','');
INSERT INTO `glpi_peripheraltypes` VALUES ('1','No-Break','');
INSERT INTO `glpi_peripheraltypes` VALUES ('2','Estabilizador','');
INSERT INTO `glpi_peripheraltypes` VALUES ('3','Unidade de Fita de Backup','');
INSERT INTO `glpi_peripheraltypes` VALUES ('4','Etiquetadora','');
INSERT INTO `glpi_peripheraltypes` VALUES ('5','Global System Position','');
INSERT INTO `glpi_peripheraltypes` VALUES ('6','Webcam','');
INSERT INTO `glpi_peripheraltypes` VALUES ('7','Reflectômetro Óptico','');
INSERT INTO `glpi_peripheraltypes` VALUES ('8','Projetor','');
INSERT INTO `glpi_peripheraltypes` VALUES ('9','Carregador Flutuador','');
INSERT INTO `glpi_peripheraltypes` VALUES ('10','Bateria para Unidades de Backup','');
INSERT INTO `glpi_peripheraltypes` VALUES ('11','Switch KVM','');
INSERT INTO `glpi_peripheraltypes` VALUES ('12','Fonte de Alimentação','');
INSERT INTO `glpi_peripheraltypes` VALUES ('13','Conversor de mídia','');
INSERT INTO `glpi_peripheraltypes` VALUES ('14','Cabo Eletrico','');
INSERT INTO `glpi_peripheraltypes` VALUES ('15','Cabo Optico','');
INSERT INTO `glpi_phonetypes` VALUES ('1','IP Phone','');
INSERT INTO `glpi_phonetypes` VALUES ('2','Celular SmartPhone','');
INSERT INTO `glpi_printertypes` VALUES ('1','Inkjet','');
INSERT INTO `glpi_printertypes` VALUES ('2','Laser','');
INSERT INTO `glpi_printertypes` VALUES ('3','Laserjet','');
INSERT INTO `glpi_printertypes` VALUES ('4','Multifuncional','');
